DEFAULT_CLASHES_MANAGER_ROLE_ID = "1158772453338775662"
DEVS_ID="699416429338034268,980156816061255690"

# -----------------------------|--------------
# ------------- DO NOT CHANGE \/ -------------
TOKEN = "$env('TOKEN')"
PUBLIC_KEY = "$env('PUBLIC_KEY')"
PORT = "$env('PORT', 3333)"
# --------------------------- /\ -------------
# ----------------------------|---------------